name: Task/Chore
description: Non-feature work (refactoring, maintenance, documentation, etc.)
title: "[Task]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for tasks that don't add new features (refactoring, docs, config changes, etc.)

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - Documentation
        - Refactoring
        - Configuration
        - Dependency Update
        - Infrastructure
        - Testing
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this task needed?
      placeholder: Explain the why...
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Task Checklist
      description: Break down the work into steps
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Step 3
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Links, references, notes...
    validations:
      required: false
