groups:
  - name: dex_pipeline_alerts
    rules:
      # --- Pipeline execution alerts ---

      - alert: PipelineDurationExceeded
        expr: dex_pipeline_duration_seconds > 2700
        for: 5m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "Pipeline execution exceeded 45-minute target"
          description: "Pipeline {{ $labels.pipeline_name }} has been running for {{ $value }}s (target: 2700s)"

      - alert: PipelineFailureRate
        expr: rate(dex_pipeline_failures_total[1h]) > 0.1
        for: 10m
        labels:
          severity: critical
          team: data-engineering
        annotations:
          summary: "High pipeline failure rate detected"
          description: "Pipeline failure rate is {{ $value | humanizePercentage }} over the last hour"

      # --- Data quality alerts ---

      - alert: DataQualityBelowThreshold
        expr: dex_data_quality_score < 0.75
        for: 15m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "Data quality score below silver layer threshold"
          description: "Quality score for {{ $labels.dataset }} is {{ $value }} (threshold: 0.75)"

      - alert: DataQualityGoldLayerLow
        expr: dex_data_quality_score{layer="gold"} < 0.90
        for: 10m
        labels:
          severity: critical
          team: data-engineering
        annotations:
          summary: "Gold layer quality below 90%"
          description: "Gold layer quality for {{ $labels.dataset }} is {{ $value }} (threshold: 0.90)"

      # --- Ingestion volume alerts ---

      - alert: LowIngestionVolume
        expr: increase(dex_jobs_ingested_total[3h]) < 5000
        for: 5m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "Low job ingestion volume this cycle"
          description: "Only {{ $value }} jobs ingested in the last 3-hour cycle (expected: 13750)"

      - alert: ZeroIngestion
        expr: increase(dex_jobs_ingested_total[6h]) == 0
        for: 5m
        labels:
          severity: critical
          team: data-engineering
        annotations:
          summary: "No data ingested for 6 hours"
          description: "Zero jobs have been ingested in the last 6 hours — pipeline may be stalled"

      # --- Deduplication alerts ---

      - alert: HighDuplicateRate
        expr: >
          rate(dex_jobs_deduplicated_total[1h])
          /
          (rate(dex_jobs_ingested_total[1h]) + rate(dex_jobs_deduplicated_total[1h]) + 1)
          > 0.30
        for: 15m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "High duplicate rate detected (>30%)"
          description: "Duplicate rate is {{ $value | humanizePercentage }} — check source connectors"

      # --- Layer loss alerts ---

      - alert: HighBronzeToSilverLoss
        expr: dex_bronze_to_silver_loss_pct > 5
        for: 10m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "Bronze→Silver data loss exceeds 5%"
          description: "{{ $value }}% of records lost during cleaning (target: <5%)"

      - alert: HighSilverToGoldLoss
        expr: dex_silver_to_gold_loss_pct > 2
        for: 10m
        labels:
          severity: warning
          team: data-engineering
        annotations:
          summary: "Silver→Gold data loss exceeds 2%"
          description: "{{ $value }}% of records lost during enrichment (target: <2%)"

      # --- Connector health alerts ---

      - alert: ConnectorDown
        expr: dex_connector_status != 1
        for: 10m
        labels:
          severity: critical
          team: data-engineering
        annotations:
          summary: "Data connector {{ $labels.connector }} is down"
          description: "Connector {{ $labels.connector }} has been unhealthy for >10 minutes"
